//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETLSoftware.DWLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimenData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimenData()
        {
            this.FattoVendita = new HashSet<FattoVendita>();
        }
    
        public int ID { get; set; }
        public System.DateTime DataValore { get; set; }
        public string GiornoNome { get; set; }
        public string GiornoTipo { get; set; }
        public Nullable<int> GiornoNumeroDelMese { get; set; }
        public Nullable<int> GiornoNumeroDellAnno { get; set; }
        public Nullable<int> SettimanaNumeroDellAnno { get; set; }
        public Nullable<int> MeseNumeroAnno { get; set; }
        public string MeseNome { get; set; }
        public Nullable<decimal> Trimestre { get; set; }
        public string TrimestreAnno { get; set; }
        public Nullable<int> Anno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattoVendita> FattoVendita { get; set; }
    }
}
