//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETLSoftware.DWLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimenProvincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimenProvincia()
        {
            this.FattoVendita = new HashSet<FattoVendita>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string NomeStato { get; set; }
        public string NomeRegione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FattoVendita> FattoVendita { get; set; }
    }
}
